include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print : true
    prefer_const_constructors : true
    prefer_final_fields : true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables : true
    use_key_in_widget_constructors : true
    prefer_is_not_empty : true
    avoid_init_to_null : true
