name: yandex_todo_app
description: "Yandex Summer School Task"
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  connectivity_plus: ^3.0.3
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icon.png"
